### ISSUE TITLE
bookworm

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#410]
RPi OS based on debian bookwork will be coming out in a few weeks / months. Let's talk about it

### I want all users to be on bookworm

There are a lot of pros to bookworm:
 - more stability
 - more support
 - #194 Python 3.11, which is significantly faster than 3.9
 - More recent sqlite3 version

I'd like to drop support for bullseye. Existing users need a migration path, and then likely a full-image reinstall.

### Plan
0. Develop some migration support for the next release #409.
1. Move nightlies to point at bookworm RPi OS. Debug when problems come up, try it out on some development Pioreactor in house.
2. Finish TODOs below
3. Write a blog post announcing the change.
4. Users probably need to re-calibrate their pumps 😔
5. Stop supporting bullseye. How do I halt the upgrade (an upgrade could break their system)?

### Todos
- [x] `pip` won't install systemwide: https://forums.raspberrypi.com/viewtopic.php?p=2128543#p2128543 solution is to rm a flag file
- [x] `RPi.GPIO` doesn't work anymore, so test `lgpio`
- [x] Migrate Python code to 3.11. Drop support for 3.9
- [x] RaspAP not working for RPi OS bookworm yet
- [x] test HAT button
- [x] import script
- [x] are the .pioreactor/../READMEs being added to the base image?
- [ ] test new `experiment_profile_runs` table

**Comment by CamDavidsonPilon** [comment]
I wonder if this would be a good time to port to DietPi, too?

**Comment by CamDavidsonPilon** [comment]
Initial script to export data:
```
#!/bin/bash

set -x
set -e

export LC_ALL=C

# script to back up Pioreactor

EXPORT_NAME=pioreactor_$(hostname)_$(date +%Y%m%d).tar.gz

pio log -m "Starting export of all data. This may take a few minutes..." -l notice -n export

# back up database
pio run backup_database --force


# gzip .pioreactor/
# export so UI can download it, this only works on leader...
tar --exclude='*.sqlite' --exclude='*.sqlite-wal'  --exclude='*.sqlite-shm' --exclude=".pioreactor/plugins/__pycache__" -zcvf /var/www/pioreactorui/static/exports/$EXPORT_NAME .pioreactor/

pio log -m "Your export is ready. Copy this link into your address bar: http://pioreactor.local/static/exports/$EXPORT_NAME" -l notice -n export
```
